### ISSUE TITLE
Q: Can you describe what SQL method is used to load the references

### ISSUE THREAD

**Issue by mdissel** [nathan-parkinson/linq2db.include#6]
Are you using left join syntax, multiple results-sets or multiple separate commands to fetch the related entities?

**Comment by nathan-parkinson** [comment]
Multiple commands are used.  I wanted to avoid the crazy queries that some ORMs use to shoehorn everything into 1 query.  

Some might prefer it in one query but my personal preference is to keep the sql sensible.

Each query uses an EXISTS function to make sure only related entities are loaded.

**Comment by mdissel** [comment]
But what about executing the separated commands into a single commend using the multi-resultset feature?

**Comment by nathan-parkinson** [comment]
Which multi-resultset feature are you referring to?  I am not aware of any such feature in Linq2DB.

I know this can be done with ADO but Linq2db.include creates linq expressions and passes them to linq2db to execute.  If there is a feature like this in linq2db that I am missing then please let me know.  

I have seen a [thread](https://github.com/linq2db/linq2db/issues/1404) on the linq2db repo discussing an nHibernate style Futures feature, this would be perfect for use in Linq2db.include

**Comment by mdissel** [comment]
Multiple resultset are added to 2.9, see https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#release-290

**Comment by nathan-parkinson** [comment]
Yep, it's nice to see this feature added.  Also worth noting is this [feature](https://github.com/linq2db/linq2db/pull/1756) which will probably render this library obselete.  

I'm waiting to see how this feature pans out before continuing any development on this library.  If it does make linq2db.include obsolete I will archive it, otherwise I will continue to add features

**Comment by sdanyliv** [comment]
@nathan-parkinson, it is important to make `Include` name?
I'm preparing eager loading release and want to stay with 'LoadWith' naming to do not conflict with EF Core in single porject. Also `ThenLoad` will be added also.

Something like this:
```cs
var filterQuery = 
	from m in db.GetTable<MainItem>()
	from m2 in db.GetTable<MainItem2>().InnerJoin(m2 => m2.Id == m.Id)
	where m.Id > 1
	select m;

var query = filterQuery
    .LoadWith(m => m.SubItems1)
        .ThenLoad(c => c.SubSubItems)
            .ThenLoad(ss => ss.ParentSubItem)
    .LoadWith(m => m.SubItems2);
```

**Comment by nathan-parkinson** [comment]
@sdanyliv, it's not important to use the name Include.  I only used that name so that it did not conflict with existing Linq2DB methods and because it was familiar for anyone who has used EF Core.

I suppose it would be easy to create an extension method wrapper that calls the new `LoadWith` and `ThenLoad` methods but with the name `Include` and `ThenInclude` so that anyone using this library would automatically get the benefit of the new built in features.

Although, I think just updating the code would be better.
